name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy storybook to Github Pages
      run: cd packages/react-slide-pane-storybook && npm install && npm run deploy-storybook -- --ci
      env:
        GH_TOKEN: MyCompany:${{ secrets.ACCESS_TOKEN }}